import { pgTable, serial, timestamp, index, pgPolicy, varchar, numeric, integer } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const healthCheck = pgTable("health_check", {
	id: serial().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
});

export const flightConfigs = pgTable("flight_configs", {
	id: serial().primaryKey().notNull(),
	warehouse: varchar({ length: 50 }).notNull(),
	weekday: varchar({ length: 10 }).notNull(),
	kantoNormal: varchar("kanto_normal", { length: 20 }),
	kansaiNormal: varchar("kansai_normal", { length: 20 }),
	kantoSpecial: varchar("kanto_special", { length: 20 }),
	kansaiSpecial: varchar("kansai_special", { length: 20 }),
	remark: varchar({ length: 500 }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("flight_configs_warehouse_idx").using("btree", table.warehouse.asc().nullsLast().op("text_ops")),
	index("flight_configs_weekday_idx").using("btree", table.weekday.asc().nullsLast().op("text_ops")),
	pgPolicy("flight_configs_允许公开删除", { as: "permissive", for: "delete", to: ["public"], using: sql`true` }),
	pgPolicy("flight_configs_允许公开更新", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("flight_configs_允许公开写入", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("flight_configs_允许公开读取", { as: "permissive", for: "select", to: ["public"] }),
]);

export const areaConfigs = pgTable("area_configs", {
	id: serial().primaryKey().notNull(),
	warehouse: varchar({ length: 50 }).notNull(),
	packageVolume: numeric("package_volume", { precision: 20, scale: 12 }).notNull(),
	kantoRatio: numeric("kanto_ratio", { precision: 5, scale:  2 }).notNull(),
	kansaiRatio: numeric("kansai_ratio", { precision: 5, scale:  2 }).notNull(),
	kantoNormalRatio: numeric("kanto_normal_ratio", { precision: 5, scale:  2 }).notNull(),
	kantoSpecialRatio: numeric("kanto_special_ratio", { precision: 5, scale:  2 }).notNull(),
	kansaiNormalRatio: numeric("kansai_normal_ratio", { precision: 5, scale:  2 }).notNull(),
	kansaiSpecialRatio: numeric("kansai_special_ratio", { precision: 5, scale:  2 }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("area_configs_warehouse_idx").using("btree", table.warehouse.asc().nullsLast().op("text_ops")),
	pgPolicy("area_configs_允许公开删除", { as: "permissive", for: "delete", to: ["public"], using: sql`true` }),
	pgPolicy("area_configs_允许公开更新", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("area_configs_允许公开写入", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("area_configs_允许公开读取", { as: "permissive", for: "select", to: ["public"] }),
]);

export const portConfigs = pgTable("port_configs", {
	id: serial().primaryKey().notNull(),
	portCode: varchar("port_code", { length: 10 }).notNull(),
	region: varchar({ length: 20 }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("port_configs_region_idx").using("btree", table.region.asc().nullsLast().op("text_ops")),
	pgPolicy("port_configs_允许公开删除", { as: "permissive", for: "delete", to: ["public"], using: sql`true` }),
	pgPolicy("port_configs_允许公开更新", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("port_configs_允许公开写入", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("port_configs_允许公开读取", { as: "permissive", for: "select", to: ["public"] }),
]);

export const routeConfigs = pgTable("route_configs", {
	id: serial().primaryKey().notNull(),
	flightNo: varchar("flight_no", { length: 20 }).notNull(),
	origin: varchar({ length: 10 }).notNull(),
	transfer: varchar({ length: 10 }),
	dest: varchar({ length: 10 }).notNull(),
	departTime: varchar("depart_time", { length: 10 }),
	arriveTime: varchar("arrive_time", { length: 10 }),
	isNextDay: varchar("is_next_day", { length: 5 }),
	secondFlight: varchar("second_flight", { length: 20 }),
	routeType: varchar("route_type", { length: 20 }).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("route_configs_flight_no_idx").using("btree", table.flightNo.asc().nullsLast().op("text_ops")),
	index("route_configs_route_type_idx").using("btree", table.routeType.asc().nullsLast().op("text_ops")),
	pgPolicy("route_configs_允许公开删除", { as: "permissive", for: "delete", to: ["public"], using: sql`true` }),
	pgPolicy("route_configs_允许公开更新", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("route_configs_允许公开写入", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("route_configs_允许公开读取", { as: "permissive", for: "select", to: ["public"] }),
]);

export const volumeEstimates = pgTable("volume_estimates", {
	id: serial().primaryKey().notNull(),
	collectDate: varchar("collect_date", { length: 20 }).notNull(),
	weekday: varchar({ length: 10 }),
	warehouse: varchar({ length: 50 }).notNull(),
	packageCount: integer("package_count").notNull(),
	weight: numeric("weight", { precision: 15, scale: 2 }),
	actualTotalVolume: numeric("actual_total_volume", { precision: 15, scale: 4 }),
	totalVolume: numeric("total_volume", { precision: 15, scale: 3 }),
	kantoTotal: numeric("kanto_total", { precision: 15, scale: 3 }),
	kansaiTotal: numeric("kansai_total", { precision: 15, scale: 3 }),
	kantoNormal: numeric("kanto_normal", { precision: 15, scale: 3 }),
	kantoSpecial: numeric("kanto_special", { precision: 15, scale: 3 }),
	kansaiNormal: numeric("kansai_normal", { precision: 15, scale: 3 }),
	kansaiSpecial: numeric("kansai_special", { precision: 15, scale: 3 }),
	airVolume: numeric("air_volume", { precision: 15, scale: 3 }),
	seaAirVolume: numeric("sea_air_volume", { precision: 15, scale: 3 }),
	isComplete: varchar("is_complete", { length: 10 }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("volume_estimates_collect_date_idx").using("btree", table.collectDate.asc().nullsLast().op("text_ops")),
	index("volume_estimates_warehouse_idx").using("btree", table.warehouse.asc().nullsLast().op("text_ops")),
	pgPolicy("volume_estimates_允许公开删除", { as: "permissive", for: "delete", to: ["public"], using: sql`true` }),
	pgPolicy("volume_estimates_允许公开更新", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("volume_estimates_允许公开写入", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("volume_estimates_允许公开读取", { as: "permissive", for: "select", to: ["public"] }),
]);

export const mainOrders = pgTable("main_orders", {
	id: serial().primaryKey().notNull(),
	collectDate: varchar("collect_date", { length: 20 }).notNull(),
	collectWeekday: varchar("collect_weekday", { length: 10 }),
	departDate: varchar("depart_date", { length: 20 }),
	departWeekday: varchar("depart_weekday", { length: 10 }),
	warehouse: varchar({ length: 50 }).notNull(),
	cargoType: varchar("cargo_type", { length: 20 }).notNull(),
	port: varchar({ length: 20 }).notNull(),
	category: varchar({ length: 50 }),
	status: varchar({ length: 20 }),
	packReq: varchar("pack_req", { length: 20 }),
	maxVolume: numeric("max_volume", { precision: 15, scale: 3 }),
	maxPieces: integer("max_pieces"),
	estVolume: numeric("est_volume", { precision: 15, scale: 3 }),
	estPieces: integer("est_pieces"),
	reqFlightDate: varchar("req_flight_date", { length: 20 }),
	actualFlightDate: varchar("actual_flight_date", { length: 20 }),
	mainNo: varchar("main_no", { length: 50 }),
	flightNo: varchar("flight_no", { length: 20 }),
	origin: varchar({ length: 10 }),
	transfer: varchar({ length: 10 }),
	dest: varchar({ length: 10 }),
	departTime: varchar("depart_time", { length: 20 }),
	arriveTime: varchar("arrive_time", { length: 20 }),
	secondFlight: varchar("second_flight", { length: 20 }),
	routeType: varchar("route_type", { length: 20 }),
	actualPieces: integer("actual_pieces"),
	actualWeight: numeric("actual_weight", { precision: 15, scale: 3 }),
	actualVolume: numeric("actual_volume", { precision: 15, scale: 3 }),
	actualBills: integer("actual_bills"),
	remark: varchar({ length: 500 }),
	issueCard: varchar("issue_card", { length: 10 }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("main_orders_cargo_type_idx").using("btree", table.cargoType.asc().nullsLast().op("text_ops")),
	index("main_orders_collect_date_idx").using("btree", table.collectDate.asc().nullsLast().op("text_ops")),
	index("main_orders_port_idx").using("btree", table.port.asc().nullsLast().op("text_ops")),
	index("main_orders_warehouse_idx").using("btree", table.warehouse.asc().nullsLast().op("text_ops")),
	pgPolicy("main_orders_允许公开删除", { as: "permissive", for: "delete", to: ["public"], using: sql`true` }),
	pgPolicy("main_orders_允许公开更新", { as: "permissive", for: "update", to: ["public"] }),
	pgPolicy("main_orders_允许公开写入", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("main_orders_允许公开读取", { as: "permissive", for: "select", to: ["public"] }),
]);

export const flightExceptions = pgTable("flight_exceptions", {
	id: serial().primaryKey().notNull(),
	departDate: varchar("depart_date", { length: 20 }).notNull(),
	flightDate: varchar("flight_date", { length: 20 }).notNull(),
	flightNo: varchar("flight_no", { length: 20 }).notNull(),
	mainNo: varchar("main_no", { length: 50 }).notNull(),
	bills: integer("bills").notNull(),
	origin: varchar({ length: 10 }).notNull(),
	transfer: varchar({ length: 10 }),
	dest: varchar({ length: 10 }).notNull(),
	exceptionReason: varchar("exception_reason", { length: 500 }).notNull(),
	remark: varchar({ length: 500 }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("flight_exceptions_depart_date_idx").using("btree", table.departDate.asc().nullsLast().op("text_ops")),
	index("flight_exceptions_flight_date_idx").using("btree", table.flightDate.asc().nullsLast().op("text_ops")),
	index("flight_exceptions_main_no_idx").using("btree", table.mainNo.asc().nullsLast().op("text_ops")),
	pgPolicy("flight_exceptions_允许公开删除", { as: "permissive", for: "delete", to: ["public"], using: sql`true` }),
	pgPolicy("flight_exceptions_允许公开更新", { as: "permissive", for: "update", to: ["public"], using: sql`true`, withCheck: sql`true` }),
	pgPolicy("flight_exceptions_允许公开写入", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`true` }),
	pgPolicy("flight_exceptions_允许公开读取", { as: "permissive", for: "select", to: ["public"] }),
]);

